# Generated by Django 2.1.4 on 2019-02-20 12:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('depreciation_period', models.IntegerField(choices=[(1, '1 year'), (2, '2 years'), (5, '5 years'), (10, '10 years')])),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='ImplementationCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MaxValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('approver', models.ManyToManyField(related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MaxValueValidator(0)])),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_tool.Investment')),
            ],
        ),
        migrations.AddField(
            model_name='implementationcost',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_tool.Investment'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_tool.Investment'),
        ),
        migrations.AddField(
            model_name='asset',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_tool.Investment'),
        ),
    ]
