# Generated by Django 2.1.4 on 2019-02-20 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MaxValueValidator(0)])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_tool.Asset')),
            ],
        ),
    ]
